run_mode: train

# reproducibility
seed: 0

# Training iteration
base_lr: 1e-4
search_lr: false
search_multiplier: 1.0
lr_scheduler_type: constant_with_decay
warmup_ratio: 0.05
warmup_min: 3000
total_samples: 1.0e+8
# iterations: ???  # decided during runtime

# regularization
criterion: cross-entropy
weight_decay: 0.01
mixup: 0.0

# log
num_history: 500
save_model: true

# wandb
use_wandb: false
draw_result: true
watch_model: false

# GPU
# device: ???  decided during runtime
ddp: false
# ddp_size: ???  decided during runtime