defaults:
  - base_train
  - _self_

# Training iteration
search_lr: false
total_samples: 100000

# log
num_history: 5
save_model: false

# wandb
use_wandb: false
draw_result: true
watch_model: false
